# Generated by Django 5.0.1 on 2024-01-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_dashboarddata_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='published',
            field=models.DateTimeField(),
        ),
    ]
