# Generated by Django 5.0.1 on 2024-01-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_dashboarddata_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='added',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='published',
            field=models.CharField(max_length=100),
        ),
    ]
