# Generated by Django 5.0.1 on 2024-01-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_dashboarddata_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='intensity',
            field=models.IntegerField(default=0),
        ),
    ]
