# Generated by Django 5.0.1 on 2024-01-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_dashboarddata_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='intensity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='published',
            field=models.DateTimeField(),
        ),
    ]
