# Generated by Django 5.0.1 on 2024-01-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_dashboarddata_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='end_year',
            field=models.DateTimeField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
