# Generated by Django 5.0.1 on 2024-01-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_dashboarddata_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='end_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
