# Generated by Django 5.0.1 on 2024-01-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_dashboarddata_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='intensity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='likelihood',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='relevance',
            field=models.IntegerField(null=True),
        ),
    ]
